/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Q66m64wRYYIMfwJP0ub7G28kAAF+lQLmBn3dfmzDIPMD6J0q0FO+QYDqzBzarupspSDVWJ4nNJEthsX6zUZMHA==
 */

/* eslint-disable */
// tslint:disable

type StatusEnum = 'AVAILABLE' | 'CHARGING' | 'REMOVED';
export type {StatusEnum}
