/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: KC4BEpOAKhHs6SQRonrYcG3B3hPiOGmX8h3Lj1MZJiun+L7Lb70R8TYZ6ek+uv5PnUG+3VLRLFZfBwKHe+ROwg==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import Chargers, {Chargers_InsertParameters} from './chargers'
import Locations, {Locations_InsertParameters} from './locations'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  chargers: {record: Chargers, insert: Chargers_InsertParameters};
  locations: {record: Locations, insert: Locations_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  Chargers,
  Chargers_InsertParameters,
  Locations,
  Locations_InsertParameters,
}
